Add and Update Team Modal
hack4impact-uiuc/south-side-weekly pull request #168
Opened 2021-10-29 01:41 UTC by zorazrr

## Summary

Create add/update teams modal, allow admin to add and update team name and team color code. 

Closes #133 

## Changes

- Create edit team modal component
- Map existing team names and colors to the modal
- API endpoint to update many teams `/api/teams/update/many`
- API endpoint to create many teams `/api/teams/many`

## Screenshots

<img width="1434" alt="Screen Shot 2021-11-02 at 7 12 17 PM" src="https://user-images.githubusercontent.com/61670566/139968585-2f4b2bca-e273-42ae-a373-8b368ae0fbee.png">

2021-10-31 17:58 UTC, amit-sawhney requested changes
Great work! 💯 There are some small things you gotta go through and fix and cleanup and then I will re-review. Don't forget to run `yarn lint` to make sure there are no lint errors. While it will pass the GitHub workflow integration, the purpose of these lint warnings is so that we maintain a clean codebase :)

2021-10-31 17:58 UTC, amit-sawhney commented on api/src/api/teams.ts
> +import { ITeam } from '../../../common';
This should not be a relative path. Instead: `import { ITeam } from 'ssw-common';`

2021-10-31 17:58 UTC, amit-sawhney commented on api/src/api/teams.ts
> +    console.log(updatedTeams);
Please remove console.log statements

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/api/teams/index.ts
> +import { ITeam } from '../../../../common';
Please fix this import and fix the lint errors. Package imports like `ssw-common`, `react`, `semantic-ui-react` should all go at the top of a file.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/api/teams/index.ts
> +import { ITeam } from '../../../../common';
And by fix this import I mean do not use `../../../../common` to get the ITeam. Use `ssw-common`

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +import React, { ReactElement, FC, useState } from 'react';
Fix lint error

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +import Swal from 'sweetalert2';
Fix lint error

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +import { createManyTeams, updateManyTeams } from '../../../api';
Fix lint error.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +import { useEffect } from 'react';
Fix lint error.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +    console.log(teams);
Remove console.log

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  }, [isOpen]);
Add proper items to dependency array and make sure this doesn't break any functionality.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const addField = () => {
Please type your return types on this function

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const removeField = (i: number) => {
Please type your return type on this function.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const updateFieldText = (i: number, text: string) => {
Lint should be complaining about this too. Type your return type here.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const updateFieldColor = (i: number, color: string) => {
Add return type.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +    const parsedNewTeams: Partial<ITeam>[] = newTeams.map(
Can you add a comment to what this does? It will make it easier to understand in the future.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +        team.name !== formValues[index].name ||
Can you clean this if statement up

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +    const isDuplicate = valuesName.some(
Stuff liking checking duplicates and removing the fields that don't belong should be handled in helper functions.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +    console.log(isDuplicate);
Remove console.log

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +        <Form id="submit-team">
Because you have a button at the bottom that has `type=submit` you could use the `onSubmit={saveForm}` callback for form.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const saveForm = (): void => {
This function could be named better.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +  const updateFieldText = (i: number, text: string) => {
Across the board, `field` is rather ambiguous. Could you improve this naming?

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/styles.scss
> +$width: 25px;
Nice use of variables.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/pages/invalid/index.tsx
> +    <TeamModal />
There is actually a space for this modal to go now. See the directory designs in figma! there is a little edit button by the column name `Team` in the directory table.

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/contexts/teams/provider.tsx
> +import { useCallback } from 'react';
This should be in the same import line as the one above

2021-10-31 17:58 UTC, amit-sawhney commented on client/src/components/Modals/EditTeam/index.tsx
> +              <div className="color-pick">
I am almost wondering if we could create a color picking component

2021-11-03 02:06 UTC, amit-sawhney approved these changes
Please resolve merge conflicts. Also please address all of my comments before merging, not just a few.

Additionally, rename the put endpoint to be `/update/many`

2021-11-05 00:15 UTC, AndrewLester approved these changes
Looks good

2021-11-05 00:15 UTC, AndrewLester commented on api/src/api/teams.ts
> +      newTeams.map(async (team) => Team.create(team)),
You can probably remove `async` from this inner function since you're not using `await` in it. I may be wrong though.

2021-11-05 00:15 UTC, AndrewLester commented on api/src/api/teams.ts
> +      changedTeams.map(async (team) => {
Same as above.

2021-11-05 00:15 UTC, AndrewLester commented on api/src/api/teams.ts
> +        message: `Failed to create teams: ${failedTeamNames.join(', ')}`,
```suggestion
        message: `Failed to update teams: ${failedTeamNames.join(', ')}`,
```

2021-11-05 00:15 UTC, AndrewLester commented on client/src/components/Modals/EditTeam/index.tsx
> +    });
Maybe create a helper function for the check here? Then you could just run `changedTeams = clonedTeams.filter(isUpdated)` or similar.

2021-11-05 03:29 UTC, merged