Update Resource Modal
hack4impact-uiuc/south-side-weekly pull request #181
Opened 2021-11-06 03:08 UTC by zorazrr

## Summary

Description of PR here...
Closes #136

## Changes

- Refactor the resource modal, including a multi-select dropdown for teams instead of checkboxes
- Add a button to schedule office hours and the Calendly pop-up

## Screenshots

<img width="1142" alt="Screen Shot 2021-11-05 at 10 05 35 PM" src="https://user-images.githubusercontent.com/61670566/140595969-96211f18-0a75-4ad9-acb5-dec731b10223.png">

<img width="1440" alt="Screen Shot 2021-11-05 at 10 08 14 PM" src="https://user-images.githubusercontent.com/61670566/140595979-b5160d09-0de7-4663-a8d0-f3b1cdb9174f.png">

2021-11-07 17:37 UTC, AndrewLester approved these changes
A few remnant `console.log`s but otherwise looks very good.

2021-11-07 20:02 UTC, bryange3 commented
Everything looks super clean! One thing is, can we get rid of the red asteriks? All of these fields are _required_ for the "Resource" modal so we don't need the asterisks to indicate it.

2021-11-09 04:22 UTC, amit-sawhney requested changes
Some CSS things to fix and then you should be good :)

2021-11-09 04:22 UTC, amit-sawhney commented on client/src/components/Modals/Resource/index.tsx
> +  // const [teams, setTeams] = useState<string[]>(formData.teams);
Remove commented out code

2021-11-09 04:22 UTC, amit-sawhney commented on client/src/pages/resources/index.tsx
> +          )}
This button style seems to be something that Bryan uses throughout the designs a few times, it would be cool if we could turn it into a component!

2021-11-09 04:22 UTC, amit-sawhney commented on client/src/pages/resources/styles.scss
> +    right: 3.78%;
This is not responsive. Look into how to flex-grow to get this into the position you would like.

2021-11-09 22:17 UTC, nkonjeti reviewed
Check with Bryan on this but I think we are not doing stars for required fields. Never mind he said this above in a comment:)

2021-11-11 04:03 UTC, amit-sawhney approved these changes
Looks good to me! 💯

2021-11-12 20:32 UTC, merged