User Feedback Modal
hack4impact-uiuc/south-side-weekly pull request #222
Opened 2021-12-03 03:12 UTC by zorazrr

## Summary

Description of PR here...
Closes #217 217

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

2021-12-06 02:45 UTC, amit-sawhney requested changes

2021-12-06 02:45 UTC, amit-sawhney commented on client/src/components/Modals/UserFeedback/index.tsx
> +    } else if (isEmpty()) {
You are calling this function twice. why not just have this in an else block?

2021-12-06 02:45 UTC, amit-sawhney commented on client/src/components/Modals/UserFeedback/index.tsx
> +  trigger: ReactElement;
ModalProps contains this trigger already I believe, no reason to redefine it.

2021-12-13 21:02 UTC, amit-sawhney approved these changes

2021-12-13 21:02 UTC, amit-sawhney commented on client/src/components/Modals/UserFeedback/index.tsx
> +    getContributorTeams();
Get rid of this lint error :)

2021-12-19 20:26 UTC, ayanmallik approved these changes
Really cool feature Zora! Great job on utilizing the rating component.

2021-12-19 23:27 UTC, AndrewLester approved these changes

2021-12-19 23:44 UTC, merged