Onboarding Wizard Confirmation Modal
hack4impact-uiuc/south-side-weekly pull request #44
Opened 2021-03-19 23:05 UTC by amit-sawhney

## Summary

Adds a popup modal to confirm that a user has scheduled a meeting for onboarding because the calendly has no callback to tell if it was clicked/scheduled

## Changes

- Add modal
- Rework user flow to prevent submit without confirmation

## Screenshots

![image](https://user-images.githubusercontent.com/66758185/111850209-a9a14300-88dd-11eb-8f7f-d99525156bc7.png)

2021-03-20 01:54 UTC, musydali requested changes
The pop-up modal has Southside written as one word and it's actually two words so it should be South Side (my typo on the Figma designs) and then instead of the button saying "Submit" it makes more sense for it to say "Complete Sign-Up" just for validation for the user so they know what that button is going to do

2021-03-20 03:11 UTC, alicesf2 requested changes

2021-03-20 03:11 UTC, alicesf2 commented on client/src/pages/wizard/Onboard8.tsx
> +            <img src={CloseSVG} alt="X" />
I suggest you use Semantic UI React's modal with the default close icon (https://react.semantic-ui.com/modules/modal/#content-close-icon) I just asked Mustafa to move the close icons to the top right cuz it's more conventional too

2021-03-20 21:27 UTC, musydali approved these changes

2021-03-20 22:05 UTC, sahithimuthyala submitted a review, later dismissed

2021-03-21 06:34 UTC, alicesf2 requested changes
<img width="309" alt="Screen Shot 2021-03-20 at 11 14 50 PM" src="https://user-images.githubusercontent.com/32147571/111896158-81047080-89e5-11eb-95c4-498bd97fcfa4.png">

photograpahing -> photographing

2021-03-22 03:58 UTC, sahithimuthyala approved these changes
💯

2021-03-23 04:32 UTC, alicesf2 approved these changes
🤩

2021-03-23 05:18 UTC, merged